version: "3.9"
services:
  web:
    build: .
    container_name: website-tracker-web
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=production
    command: gunicorn -w 2 -b 0.0.0.0:5000 web.server:app 